name: CI

on:
  # Trigger per l'esecuzione automatica ogni giorno alle 23:58
  schedule:
    - cron: "58 23 * * *"  # Esecuzione alle 23:58 ogni giorno
  
  # Trigger su push o pull request sulla branch main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Trigger manuale
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Aggiungere lo step per verificare i file JSON
      - name: Get catalogo files
        run: |
          curl -o catalogoWindows.json https://raw.githubusercontent.com/AMStore-na/Store/refs/heads/main/catalogoWindows.json
          curl -o old_catalogoWindows.json https://raw.githubusercontent.com/AMStore-na/Store/refs/heads/main/old_catalogoWindows.json

      # Aggiungere lo step per confrontare e aggiornare il file
      - name: Compare and update JSON
        run: |
          # Controllo se i file sono uguali
          diff catalogoWindows.json old_catalogoWindows.json || {
            echo "Files are different, updating old_catalogoWindows.json";
            cp catalogoWindows.json old_catalogoWindows.json;
            # Pushare la modifica
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add old_catalogoWindows.json
            git commit -m "Aggiornamento old_catalogoWindows.json"
            git push
          }
