name: Aggiornamento Catalogo

on:
  push:
    paths:
      - 'ScriptPython/AggiornamentoCatalogo.py' # Avvia il workflow solo se viene modificato Json/mods.json
  workflow_dispatch: # Permette di avviare manualmente il workflow
  schedule:
    - cron: '55 23 * * *' # Esegui il workflow ogni giorno alle 23:55

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Specifica la versione di Python

    - name: Install dependencies
      run: pip install requests python-telegram-bot==20.0 PyGithub # Aggiungi PyGithub qui

    - name: Esegui lo script monitor
      run: |
            python ScriptPython/AggiornamentoCatalogo.py
env:
  GITHUB_TOKEN: ${{ secrets.AGGIORNAMENTO }}


