name: CI

on:
  schedule:
    - cron: "58 23 * * *"  # Esecuzione alle 23:58 ogni giorno

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Aggiungere lo step per ottenere i file catalogo
      - name: Get catalogo files
        run: |
          curl -o catalogoWindows.json https://raw.githubusercontent.com/AMStore-na/Store/refs/heads/main/catalogoWindows.json
          curl -o old_catalogoWindows.json https://raw.githubusercontent.com/AMStore-na/Store/refs/heads/main/old_catalogoWindows.json

      # Aggiungere lo step per confrontare e aggiornare il file
      - name: Compare and update JSON
        run: |
          diff catalogoWindows.json old_catalogoWindows.json || {
            echo "Files are different, updating old_catalogoWindows.json";
            cp catalogoWindows.json old_catalogoWindows.json;
            
            # Configurazione git con il token
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git remote set-url origin https://x-access-token:${{ secrets.AGGIORNAMENTO }}@github.com/AMStore-na/Store.git

            # Aggiungere e fare commit dei cambiamenti
            git add old_catalogoWindows.json
            git commit -m "Aggiornamento old_catalogoWindows.json"
            git push
          }

